sudo: required
services:
  - docker

before_install:
  - docker build -t topriddy/react-test -f ./client/Dockerfile.dev ./client/

scripts:
  - docker run topriddy/react-test npm test -- --coverage

after_success:
  - docker build -t topriddy/multi-client ./client  
  - docker build -t topriddy/multi-nginx ./nginx  
  - docker build -t topriddy/multi-server ./server  
  - docker build -t topriddy/multi-worker ./worker  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push topriddy/multi-client
  - docker push topriddy/multi-nginx
  - docker push topriddy/multi-server
  - docker push topriddy/multi-worker