sudo: required
services:
  - docker

before_install:
  - docker build -t topriddy/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run topriddy/react-test npm test -- --coverage

after_success:
  - docker build -t topriddy/multi-client ./client  
  - docker build -t topriddy/multi-nginx ./nginx  
  - docker build -t topriddy/multi-server ./server  
  - docker build -t topriddy/multi-worker ./worker  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push topriddy/multi-client
  - docker push topriddy/multi-nginx
  - docker push topriddy/multi-server
  - docker push topriddy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-533951633431
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY